### ISSUE TITLE
Crash when the map ends.

### ISSUE THREAD

**Issue by Awoolanche** [LumpBloom7/hishigata#25]
The game crashes when the played beatmap ends on hishigata mode. Build 2020.1203.0. Lazer build 2020.1212.0.
[runtime.log](https://github.com/LumpBloom7/hishigata/files/5710125/runtime.log)

**Comment by LumpBloom7** [comment]
Sorry, but I am unable to reproduce the error.
The runtime logs don't seem to show any errors either.

Can you double check everything to make sure that the problem isn't on your end, or to at least try to get another log for me.

**Comment by Awoolanche** [comment]
Nevermind. I turned my laptop on to make another log, but it seems the issue magically fixed itself after restart. Issue solved.
